# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c269d4431fb32509604ba01c2f938387a60a8b6222cbfdc2f46e7e8735d6a28571616879bbd8ac3b1b7ed556dfc34a5ed6b72605717c5402049015a61a4dd75a

test:
  secret_key_base: 3f8707d26338dcf4a98aeab47fc73da45b79c2b198b9fe6d8c3703bd3af2392a45791a128be92005a21b21170aaa8449018744bddd664e94bc1f07aa7ced6d37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
